---
apiVersion: v1
kind: Service
metadata:
  annotations:
    fabric8.io/git-commit: 6e45629d1e1d3fae885296588b65a3c919392233
    fabric8.io/iconUrl: img/icons/camel.svg
    fabric8.io/git-branch: master
    prometheus.io/scrape: "true"
    prometheus.io/port: "9779"
  labels:
    expose: "true"
    app: location-service
    provider: fabric8
    version: 1.0.0-SNAPSHOT
    group: com.redhat
  name: location-service
spec:
  ports:
  - name: http
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: location-service
    provider: fabric8
    group: com.redhat
